apiVersion: v1
kind: Service
metadata:
  name: {{ include "mf-metrics-ingestion.fullname" . }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ include "mf-metrics-ingestion.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
