name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  buildAndPublish:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 20.19.0
      PNPM_VERSION: 10.26.0

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Enable corepack & setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@${{ env.PNPM_VERSION }} --activate

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Restore Turbo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ runner.os }}-

      - name: Check
        run: pnpm check

      # - name: Run tests
      #   run: pnpm test

      - name: Build
        run: pnpm turbo run build --cache-dir=.turbo
        env:
          # 动态获取仓库名并传给 Vite
          VITE_APP_BASE: /${{ github.event.repository.name }}/

      # —— ① 构建产物下载（Artifact）——
      - name: Upload build artifact for main
        uses: actions/upload-artifact@v4
        with:
          name: main-dist
          path: apps/main/dist

      - name: Upload build artifact for vue
        uses: actions/upload-artifact@v4
        with:
          name: vue-dist
          path: apps/vue/dist

      - name: Upload build artifact for react
        uses: actions/upload-artifact@v4
        with:
          name: react-dist
          path: apps/react/dist

      # —— ② 部署到 GitHub Pages（Preview）——
      # - name: Upload main app
      #   run: |
      #     aws s3 sync apps/main/dist s3://xxx/main

      # - name: Upload vue app
      #   run: |
      #     aws s3 sync apps/vue/dist s3://xxx/vue

      # - name: Upload react app
      #   run: |
      #     aws s3 sync apps/react/dist s3://react/vue

      - name: Upload Pages artifact for main
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/main/dist

  deploy:
    needs: buildAndPublish
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
